name: build
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install pnpm 🤏🏻
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
          run_install: true

      - name: Lint 🧹
        run: |
          pnpm run lint

      - name: Test 🧪
        run: |
          pnpm run test:coverage

      - name: Build 🔧
        run: |
          pnpm run build:min

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docs 📖
        run: |
          pnpm run docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs
